### ISSUE TITLE
Out of band writing

### ISSUE THREAD

**Issue by mojodna** [sat-utils/sat-stac#34]
I would like to handle writing Catalog and Item JSON representations. 2 (or more?) things would facilitate this:

1. a helper for generating JSON representations (effectively `json.dumps(self.data)`)
2. eliminating the check for saved catalogs prior to adding sub-catalogs

Is there a reason that catalog hierarchies can't be assembled in memory before being written out?

**Comment by matthewhanson** [comment]
@mojodna Thanks.
I thought I already had a helper for that, but it's for creating GeoJSON of Items: https://github.com/sat-utils/sat-stac/blob/master/satstac/items.py#L102

I totally agree about eliminating the check. The initial use case was for doing incremental updates to an existing catalog, but as you can see it's quite inefficient if wanting to batch write a bunch of Items.

I was thinking of adding a function to `Items` to write out a complete Catalog - so this would create all the sub-catalogs in memory first based on all the Items, then write them out, and wouldn't need to check for catalogs before adding (the assumption is that this is a new catalog, or at least a whole new branch from an existing catalog). Would this be sufficient?

**Comment by mojodna** [comment]
> Would this be sufficient?

Yup, that sounds good to me.

**Comment by matthewhanson** [comment]
Closing and copying the same text I posted in https://github.com/sat-utils/sat-stac/issues/47#issuecomment-577999341

---
I'm closing this, as I think [PySTAC](https://github.com/azavea/pystac) is the better library for creating static catalogs, it's much more efficient.

I'm continuing to use sat-stac for as the basis for downstream projects like sat-search rather than PySTAC right now.  Because sat-stac doesn't explicitly define variables mapped to STAC fields, it's not tightly coupled to the changing STAC spec and therefore easy to update....and also means a single version of sat-stac may be compatible with several STAC versions.
