### ISSUE TITLE
allow specifying of catalog save path

### ISSUE THREAD

**Issue by matthewhanson** [sat-utils/sat-stac#35]
When adding an Item the user can specify a pattern for path and filename, however when adding a catalog or collection it simply uses the ID of the new entity as the directory. This should be able to be specified.

**Comment by matthewhanson** [comment]
Specifying the save path would allow a user to add a catalog to another catalog via a series of linked catalogs, which doesn't seem a likely use case. And using the ID as the current directory conforms to [STAC Best Practices](https://github.com/radiantearth/stac-spec/blob/dev/catalog-spec/catalog-best-practices.md), so not sure I see a reason to change it.

Closing this issue.

**Comment by drwelby** [comment]
I have a use case and am not sure the best way to handle it.

I have a catalog that is sorted spatially, like:

`catalog/tiles/<row>/<column>/<item_id>.json`

I'd like to make a second catalog sorted by time:

`catalog/dates/<year>/<month>/<day>/catalog.json`

where `catalog.json` just has links to the Items in the other catalog.

It would be great to be able to use a similar `path` construct here. Otherwise, what's the best way to make these catalogs with this kind of structure that don't have items in them?

**Comment by matthewhanson** [comment]
@drwelby  Hmm, interesting use case. You basically want multiple "views" into the catalog Items right?

There's no way to use the `path` feature outside of items, when you add an item is creates all those sub-catalogs. You could take that `add_items` code as a starting point and edit it to do what you want.    

I think I might start by making the first catalog, then getting the items for a certain date/time, creating the new sub-catalogs manually, and then adding the links to the previous items.
