### ISSUE TITLE
Reading STAC Items from dict

### ISSUE THREAD

**Issue by geospatial-jeff** [sat-utils/sat-stac#47]
When `satstac.Item` loads a dictionary it is unable to access any collection-level information.  This is because both `satstac.Item._collection` and `satstac.Item.filename` are set to `None` which casues `satstac.Item.collection()` to always return `None`.  See the code snippet below.

```python
from satstac import Item, Collection
import requests

infile = "https://landsat-stac.s3.amazonaws.com/landsat-8-l1/026/038/2014-10-30/LC80260382014303LGN00.json"

# Opening item from url (this works)
item_from_url = Item.open(infile)
assert not item_from_url._collection
assert item_from_url.filename == infile
assert type(item_from_url.collection()) == Collection
print(item_from_url.eobands)

# Opening item from dict (this doesn't work)
data = requests.get(infile).json()
item_from_dict = Item(data)
# Both item._collection and item.filename are None which makes item.collection() always return None
assert not item_from_dict._collection
assert not item_from_dict.filename
assert not item_from_dict.collection()

# This prevents accessing collection-level information
print(item_from_dict.eobands)
```
This prints:

```
> [{'name': 'B1', 'common_name': 'coastal', 'gsd': 30, 'center_wavelength': 0.44 .........
> []
```

My personal use-case with this is for [stac-updater](https://github.com/geospatial-jeff/stac-updater).  Stac-updater uses the STAC Item itself as the message between AWS resources and I'd like to be able to read that message with sat-stac and parse out collection-level information (in this instance eobands is stored at the collection level as commons).  For example:

```python
from satstac import Item

def handler(event, context):
    item = Item(event)
    print(item.eobands)
```

**Comment by geospatial-jeff** [comment]
Potential fix [here](https://github.com/geospatial-jeff/sat-stac/commit/4792bf5aa98561b339220946efcb83e01af69c17).  It does cause the `test_item.Test.test_init_without_collection` test case to fail but that is because the `self` link is relative whereas the STAC spec indicates `self` should be absolute.

**Comment by matthewhanson** [comment]
Thanks for bringing this up @geospatial-jeff.   This really arises from a design issue, where if you are opening STAC Items (or Catalogs or Collections) from a dictionary, the assumption is that the hierarchical links are not valid.  In that case, in order to solve the problem of collection being None, you need to hand in collection as a keyword:

```
item_from_dict = Item(data, collection=collection_data)
```

The idea was that if you are loading from dictionaries it is because you are going to be creating a catalog, not reading from one. If you read from one then you would use the Open() function.

That being said, I've been thinking about how to refactor sat-stac in how it handles some of this stuff.  The hierarchies, and being able to handle relative and absolute links certainly does make for a bit of a complicated mess.  Definitely open to suggestions for changing things, and I can see how it would be nice for stac-updater to create an Item from the event payload.  For now, you could work-around by loading the collection metadata yourself and handing that to the Item init function.

**Comment by geospatial-jeff** [comment]
@matthewhanson Thanks for your response!  I could tell from some of the comments in the codebase that you were thinking about better ways of doing it.

> For now, you could work-around by loading the collection metadata yourself and handing that to the Item init function.

I did something similar before I knew that sat-stac had a method to get `eobands` which checked both the item and collection.  I found the issue with `eobands` while refactoring my code to use sat-stac instead of the method I wrote.  For now I will go back to that method!

**Comment by matthewhanson** [comment]
I'm closing this, as I think [PySTAC](https://github.com/azavea/pystac) is the better library for creating static catalogs, it's much more efficient.

I'm continuing to use sat-stac for as the basis for downstream projects like sat-search rather than PySTAC right now.  Because sat-stac doesn't explicitly define variables mapped to STAC fields, it's not tightly coupled to the changing STAC spec and therefore easy to update....and also means a single version of sat-stac may be compatible with several STAC versions.
