### ISSUE TITLE
KeyError: 'collections' opening itemCollection

### ISSUE THREAD

**Issue by scottyhq** [sat-utils/sat-stac#65]
sat-stac version '0.4.0'

```python
from satstac import ItemCollection
limit=500
url = f'https://cmr.earthdata.nasa.gov/cmr-stac/NSIDC_ECS/collections/C1262010979-NSIDC_ECS/items?limit={limit}'
items = ItemCollection.open(url)
print(len(items))
print(items[0], items[1])
```

```pytb
~/miniconda3/envs/intake-stac-dev/lib/python3.7/site-packages/satstac/itemcollection.py in open(cls, filename)
---> 60         collections = [Collection(col) for col in data['collections']]
     61         items = [Item(feature) for feature in data['features']]
     62         collections = [item.collection() for item in items]

KeyError: 'collections'
```

Can be fixed commenting these lines:
https://github.com/sat-utils/sat-stac/blob/42b6743a1c9b57461e8b06d440e34a8aff77522e/satstac/item.py#L31-L33 

And changing this:
https://github.com/sat-utils/sat-stac/blob/42b6743a1c9b57461e8b06d440e34a8aff77522e/satstac/itemcollection.py#L58-L59
to `collections = [item.collection() for item in items]`

But maybe this is an issue with the catalog rather than sat-stac? cc @matthewhanson

**Comment by matthewhanson** [comment]
The problem here is that sat-stac is treating the input file as a [single file STAC catalog](https://github.com/radiantearth/stac-spec/tree/master/extensions/single-file-stac) which is how sat-search saves search results. That way all the metadata, including the collection the item belongs to, is within the catalog.

One way to approach this would be to read the JSON first then add in an empty collections array. However, I can also see that it would be useful for collections not to be required.  I believe sat-search strips the `collection` link from the item, but it wouldn't have to and then you'd still have a reference to the collection. Also could be used to open up a set of items which don't belong to a collection.

**Comment by scottyhq** [comment]
> Also could be used to open up a set of items which don't belong to a collection.

This seems like it could be particularly useful. Sounds like there are a few options for remedies, whatever you think is best @matthewhanson !
